### ISSUE TITLE
Add support for bends in tabs

### ISSUE THREAD

**Issue by dario-loi** [sitandr/conchord#1]
It would be nice to have the notation for a bending (as an upgoing arrow with an attached number that indicates how many tones the note should shift up), alternatively, the ability to the "b" string to a note to indicate a bend like:

```
7/6-2 7/4-3 9/3-2 7/4-3 9/3-2b
```

Would suffice.

**Comment by sitandr** [comment]
Thanks for your feedback!

Sure, this is an important thing I will add as soon as I'll be able to work on package again.

Just in case, you can use "code mode" and cetz to add them right now (btw, if you do, please write there, I would be grateful for the snippet to do the spacing right). But, of course, embedding code would be quite ugly, so it should be definitely a built-in thing.

**Comment by sitandr** [comment]
I added bends with possible text and possible bend-releases, they look like this:

```
1/3bfullr+2/5-2 1/2b1/2-1 
```

![image](https://github.com/sitandr/conchord/assets/60141933/933d7592-ad7c-446a-a143-c4564e56045a)

I know there are other variations of bends, but afaic these should be the most common ones. I'm planning to add more of them in future. If you think there are ones that should be also added right now, feel free to reopen the issue.
