### ISSUE TITLE
Fret number doesn't follow font

### ISSUE THREAD

**Issue by federicomrc** [sitandr/conchord#3]
As title says fret number doesn't follow text font. This is usually hard to notice if font is small and/or quite simple, but if using a more stylized font as the one used in Real Book this difference can be seen.

It think that this is due to the use of the `raw` function to display it at line `lib.typ:88`. 

Aside from this I really like your library!

**Comment by sitandr** [comment]
Hello there!

Yes, I intentionally use raw function there for a better look. This also helps to customise the look of fret numbers without changing the properties of other text (the labels in case of chord diagrams). This would be much better once there will come user-defined types, but this is my solution for now. 

You can set the font you like with classical

```typ
#show raw: set text(font: <your font>)
```

So this is intended, but I should have documented it better. Or is there something else that is important for you?

**Comment by sitandr** [comment]
Thank you for your feedback! I wrote a paragraph about it in README, so I will close this issue for now. If you are not satisfied with this solution, feel free to reopen the issue. I will be glad to hear any suggestions to make it better.
